window.TOOLTIPS = {
  base_url: 'URL principal de Brightspace. Ej: https://bloqueneon.uniandes.edu.co',
  auth_strategy: 'Cómo el server se autentica con Brightspace.',
  auth_browser: 'Usa Playwright para automatizar el login. Ideal para Microsoft SSO (Azure AD).',
  auth_api_token: 'El más simple: requiere un token Valence del panel de administración.',
  auth_headless: 'HTTP automático con usuario/contraseña. Soporta Duo Push y TOTP.',
  auth_session_cookie: 'Pegar cookies manualmente desde DevTools del browser.',
  preset_microsoft: 'Rellena automáticamente los selectores CSS para Azure AD / Office 365.',
  username_ref: 'Variable de entorno que contiene el usuario. Ej: env:BRIGHTSPACE_USERNAME',
  password_ref: 'Variable de entorno que contiene la contraseña.',
  totp_secret_ref: 'Variable de entorno con el secreto TOTP base32 del QR code.',
  tz: 'Zona horaria IANA para mostrar fechas. Ej: America/Bogota o Europe/Madrid.',
  locale: 'Idioma en que el MCP server muestra los resultados de los tools.',
  output_format: 'Markdown: tablas y headers para Claude/Cursor. Plain: texto plano legacy.',
  writes_enabled: 'Habilita submit_assignment, post_discussion_reply, mark_announcement_read.',
  cache_hit_rate: '% de solicitudes servidas desde caché sin llamar a la API de Brightspace.',
  cache_items: 'Número de entradas actualmente almacenadas en el caché en memoria.',
  session_expires: 'Tiempo hasta que la sesión de Brightspace expire y requiera re-autenticación.',
  due_date: 'Fecha y hora límite de entrega, convertida a tu zona horaria configurada.',
  grade_percent: 'Porcentaje calculado como (puntos obtenidos / puntos máximos) × 100.',
  audit_log: 'Historial de operaciones de escritura (entregas, posts). Args secretos redactados.',
  diagnostics_uptime: 'Segundos que lleva corriendo este proceso del MCP UI server.',
  mfa_strategy: 'Método de autenticación de doble factor soportado por tu universidad.',
  headless: 'true = Playwright corre en background sin abrir ventana. false = visible (debug).',
  profile_name: 'Nombre del perfil en config.yaml. Puede tener múltiples perfiles para distintas instituciones.',
  login_url: 'URL de la página de login. Por defecto: {base_url}/d2l/login',
  reauth_button: 'Fuerza una nueva autenticación con Brightspace sin cerrar sesión del MCP.',
  cache_clear: 'Elimina todas las entradas del caché. La próxima consulta irá a la API de D2L.',
  sse_events: 'El servidor envía actualizaciones en tiempo real al browser sin recargar.',
  port: 'Puerto TCP donde corre el dashboard. Por defecto: 9876.',
  open_flag: 'Abre automáticamente el browser al iniciar el dashboard.',
};
